# Common definitions in use between NMAKE and GNUMake Makefiles.

# Binary executable name.
OUTPUT = sand-sim

CC = clang

# Use C23 standard, level 2 optimization level, and very high warning level.
# We call C23 as C2x for compatability with older MinGW versions (Ex: Ubuntu 26.04 in 2026-2027 only comes with MinGW 13!)
CFLAGS = -std=c2x \
         -O2 \
         -Wall \
         -Wextra \
         -Wpedantic \
         -Wconversion \
         -Wdouble-promotion \
         -Wfloat-equal \
         -Wmultichar \
         -Wnull-dereference \
         -Wshadow \
         -Wstrict-prototypes \
         -Wold-style-definition \
         -Wmissing-include-dirs \
         -Wnested-externs \
         -Wunused-macros \
         -Wbad-function-cast \
         -Wcast-qual \
         -Wwrite-strings
#-Wmissing-prototypes (Bugged in SDL3 with mingw)

# Flags for using Address and LeakSanitizer from LLVM.
ASAN_FLAGS = -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
DEBUG_CFLAGS = $(CFLAGS:O2=O0 -g -gpubnames $(ASAN_FLAGS))

# Linker flags common to all build targets. 
# (There are none... left empty for now.)
LDFLAGS =
DEBUG_LDFLAGS = $(LDFLAGS) $(ASAN_FLAGS)

# Manually listed source files. 
#
# GNUmake Keyword 'wildcard' is an extension and therefore not portable across 
# NMAKE. For this reason, source files are listed manually here.
SRCS = src/main.c \
       src/sandsim_cli.c \
       src/sandbox.c \
       src/tile.c \
       src/gui.c \
       src/utils.c

# For now, assume all sources define a public API, with the exception of main.c.
HDRS = $(SRCS:src/main.c= )

# Object extension matters to GCC, and for Windows its a convention to stick to.
GNU_OBJS = $(SRCS:.c=.o)
WIN_OBJS = $(SRCS:.c=.obj)
DEBUG_OBJS = ${SRCS:.c=_debug.o}

# Targets to delete on clean.
RM_TARGETS = *.out *.o *.obj $(GNU_OBJS) $(WIN_OBJS) $(DEBUG_OBJS) *.exe *.dll LICENSE.* sand-sim*